{% set name = "esi-acme" %}
{% set version = "2026.6" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7f46314894c106d5b12155f2e3ae36d71737a71d75c3dd49ba3ff86c84d772e8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pyyaml
    - toml
    - setuptools
  run:
    - cloudpickle >2.2
    - dask >=2022.12.1,<=2026.6.0
    - dask-jobqueue >=0.8,<1.0
    - h5py >=3,<4
    - numpy >=1.0,<3.0
    - pip
    - psutil
    - python >={{ python_min }},<3.15
    - toolz >=0.12
    - tqdm >=4.31

test:
  imports:
    - acme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://esi-acme.readthedocs.io/en/latest/
  summary: Asynchronous Computing Made ESI
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pantaray
